name: Build and Upload APK

on:
  push:
    branches: [ "LKH-ANDROID" ]
  pull_request:
    branches: [ "LKH-ANDROID" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run :
        working-directory: ./MyApplication

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Test
      run: pwd && ls -a && tree
      
    - name: Upload apk
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: /home/runner/work/Travling/Travling/MyApplication/app/build/outputs/apk/release/apk-release-unsinged.apk
